jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.10
    strategy:
      matrix:
        macos-py310-cover:
          IMAGE_NAME: macOS-10.15
          PYTHON_VERSION: 3.10
          TOXENV: py310-cover
    pool:
      vmImage: $(IMAGE_NAME)
    timeoutInMinutes: 0
    steps:
      - template: ../steps/tox-steps.yml
